apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
  name: demo-prometheus-rule
  namespace: redhat-rhoam-observability
spec:
  groups:
    - name: DemoPrometheusRuleGroup
      rules:
        - alert: DemoPrometheusRule
          annotations:
            description: >-
              The addon-managed-api-service-parameters secret has been removed
              from the redhat-rhoam-operator namespace, this secret should be
              generated and managed by Hive
            sop_url: >-
              https://gitlab.cee.redhat.com/rhcloudservices/integreatly-help/blob/master/sops/rhoam/alerts/AddonManagedApiServiceParameters.asciido
          expr: >-
            absent(kube_secret_info{namespace='redhat-rhoam-operator',secret='addon-managed-api-service-parameters'}
            == 1)
          for: 5m
          labels:
            product: rhoam
            severity: warning
